# Generated by Django 3.1.2 on 2021-04-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthDate',
            new_name='birth_date',
        ),
    ]
