# Generated by Django 3.1.2 on 2021-05-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity_result',
            name='training',
        ),
        migrations.AddField(
            model_name='activity_training',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
