# Generated by Django 3.1.2 on 2021-05-07 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20210506_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity_result',
            name='activity',
        ),
        migrations.AddField(
            model_name='activity_result',
            name='solution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.solution'),
        ),
    ]
