# Generated by Django 3.1.2 on 2021-05-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20210501_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='save_session',
            field=models.BooleanField(default=False),
        ),
    ]
