# Generated by Django 3.1.2 on 2021-05-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_solution_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
