# Generated by Django 3.1.2 on 2021-05-07 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_auto_20210507_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity_result',
            old_name='isCompleted',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='activity_training',
            old_name='isCompleted',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='isCompleted',
            new_name='is_completed',
        ),
    ]
