# Generated by Django 3.1.2 on 2021-05-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_auto_20210507_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('Memory', 'Memory')], default='None', max_length=10),
        ),
    ]
