# Generated by Django 3.1.2 on 2021-05-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_activity_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.TextField(default='Title'),
        ),
    ]
