# Generated by Django 3.1.2 on 2021-05-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_activity_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('None', 'None'), ('Memory', 'Memory'), ('Attention', 'Attention'), ('Calculus', 'Calculus')], default='None', max_length=10),
        ),
    ]
