# Generated by Django 3.1.2 on 2021-05-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_auto_20210516_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='description',
            field=models.TextField(default='Training'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(default='Title', max_length=100),
        ),
    ]
