# Generated by Django 3.1.2 on 2021-05-16 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_auto_20210516_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='is_completed',
        ),
        migrations.CreateModel(
            name='Patient_training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.patient')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.training')),
            ],
        ),
    ]
