# Generated by Django 3.1.2 on 2021-05-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_training_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_training',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
