# Generated by Django 3.1.2 on 2021-05-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0016_activity_result_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_result',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient_training',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
