# Generated by Django 3.1.2 on 2021-05-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0019_auto_20210523_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('None', 'None'), ('Memory', 'Memoria'), ('Attention', 'Atencion'), ('Calculus', 'Cálculo'), ('Perception', 'Percepción'), ('Language', 'Lenguaje')], default='None', max_length=10),
        ),
    ]
