# Generated by Django 3.1.2 on 2021-05-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0024_test_result_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
