# Generated by Django 3.1.2 on 2021-05-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0025_patient_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
