# Generated by Django 3.1.2 on 2021-06-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0026_patient_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='mental_test',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
