# Generated by Django 3.1.2 on 2021-06-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0028_auto_20210601_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='comments',
            field=models.TextField(max_length=400),
        ),
    ]
