# Generated by Django 3.1.2 on 2021-06-02 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0029_auto_20210601_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.date(2021, 6, 1), max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='comments',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
